# Generated by Django 4.2.2 on 2023-06-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("FREE", "Free"), ("Premium", "Premium")],
                default="FREE",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, default='2023-06-30 15:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
