# Generated by Django 4.2.2 on 2023-06-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                choices=[("FREE", "Free"), ("Premium", "Premium")],
                default="FREE",
                max_length=200,
            ),
        ),
    ]
