# Generated by Django 4.2.2 on 2023-07-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_order_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2023-06-30 15:30:00"),
            preserve_default=False,
        ),
    ]
